### ISSUE TITLE
Pie Chart Labels Orientation

### ISSUE THREAD

**Issue by tamsler** [cyberpython/AwesomeChartJS#2]
Some of the pie chart labels are rendered upside down. Is it possible to render them horizontally instead of aligning them with the pie radius?

Sample Code:

``` javascript
var mychart = new AwesomeChart('chart_canvas');
mychart.chartType = "pie";
mychart.data = [200,3];
mychart.labels = ["foo","bar"];
mychart.colors = ['#006CFF', '#FF6600'];
mychart.randomColors = true;
mychart.draw();
```

In the above case, the "foo" label is rendered upside down.

Screen capture http://goo.gl/kBhgm

**Comment by cyberpython** [comment]
e9e95d74ed33f9e255b93556fbcf5e2f420a7cf7 fixes the orientation problem. 

It would certainly be possible to render the labels horizontally, but further calculations would be required to find the resulting pie radius (taking into account the placement and width of the labels).

**Comment by cyberpython** [comment]
The e9e95d74ed33f9e255b93556fbcf5e2f420a7cf7 commit fixes the label orientation problem.

**Comment by cyberpython** [comment]
1819698f8cd61c8e666c5c390100b982720ad20b fixes exploded pie chart labels.

Example:
http://jsfiddle.net/VBnrg/1/

**Comment by tamsler** [comment]
Awesome!! Thank you.

**Comment by cyberpython** [comment]
Thank you for spotting and reporting the bug!!
